name: Trigger auto deployment for containerapps

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]

  # Allow mannually trigger 
  workflow_dispatch:

permissions:
      id-token: write  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        with:
          path: main

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Log in to container registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: heroapp.azurecr.io
      #     username: ${{ secrets.REGISTRY_USERNAME }}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}

      # - name: Build and push container image to registry
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: heroapp.azurecr.io/pythonapp:${{ github.sha }}
      #     file: ./src/python/Dockerfile

      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Installing CLI-beta for OpenID Connect
        run: |
          cd ../..
          CWD="$(pwd)"
          python3 -m venv oidc-venv
          . oidc-venv/bin/activate
          echo "activated environment"
          python3 -m pip install -q --upgrade pip
          echo "started installing cli beta"
          pip install -q --extra-index-url https://azcliprod.blob.core.windows.net/beta/simple/ azure-cli
          echo "***************installed cli beta*******************"
          echo "$CWD/oidc-venv/bin" >> $GITHUB_PATH
          
      - name: 'Az CLI login'
        uses: azure/login@v1.4.0
        with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}

      - name: Build and push container image to registry
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            echo "Building and pushing image to registry"
            az acr build -t pythonapp:${{ github.sha }} -r heroapp.azurecr.io ./src/python


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          azcliversion: 2.20.0
          inlineScript: |
            echo "Installing containerapp extension"
            az extension add --source https://workerappscliextension.blob.core.windows.net/azure-cli-extension/containerapp-0.2.0-py2.py3-none-any.whl --yes
            echo "Starting Deploying"
            az containerapp update -n pythonapp -g HeroAppSample -i heroapp.azurecr.io/pythonapp:${{ github.sha }} --registry-login-server heroapp.azurecr.io --registry-username  ${{ secrets.REGISTRY_USERNAME }} --registry-password ${{ secrets.REGISTRY_PASSWORD }} --debug
